### ISSUE TITLE
Debian repository has moved to archive

### ISSUE THREAD

**Issue by tagdara** [bcsanford/unifi-pimd#1]
The pimd package can no longer be found at http.us.debian.org, and requires archive.debian.org now.

**Comment by bcsanford** [comment]
Thanks, i only wish i had seen this before googling to find exactly that information.
it should be fixed now at commit https://github.com/bcsanford/unifi-pimd/commit/b3e8e07b43a54e817f19d6dd4c75fa623f00edcb
